name: michaelhaslim
favicon: null
layout_spectrum: 0.7190107116475701
typography_spectrum: 0.5298249453771859
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.522280290722847
  lightness: 0.7305490372236818
  saturation: 0.3952027475461364
  rhythmicContrast: 0.741480411728844
purpose: []
